Detect merge commits and auto tag release commits. Create Pull Request.

diff --git a/.github/workflows/ArtifactsDownload.yml b/.github/workflows/ArtifactsDownload.yml
--- a/.github/workflows/ArtifactsDownload.yml
+++ b/.github/workflows/ArtifactsDownload.yml
@@ -21,6 +21,9 @@ on:
   workflow_dispatch:
 
 jobs:
+  Prepare:
+    uses: pyTooling/Actions/.github/workflows/PrepareJob.yml@r6
+
   Build-1:
     name: ${{ matrix.os.icon }} Build 1 on ${{ matrix.os.name }} - Upload artifact
     runs-on: ${{ matrix.os.image }}
@@ -335,3 +338,69 @@ jobs:
             lib/.library
             lib/gui/main.py
             lib/gui/dialog.py
+
+
+  TriggerTaggedRelease:
+    uses: pyTooling/Actions/.github/workflows/TagReleaseCommit.yml@r6
+    needs:
+      - Prepare
+      - Verify-ProjectRoot
+      - Verify-SubDirectory
+      - Verify-MultipleArtifacts
+      - Verify-legacy
+    if: needs.Prepare.outputs.is_release_commit == 'true' && github.event_name != 'schedule'
+    permissions:
+      contents: write  # required for create tag
+      actions:  write  # required for trigger workflow
+    with:
+      version:  ${{ needs.Prepare.outputs.version }}
+      auto_tag: ${{ needs.Prepare.outputs.is_release_commit }}
+      workflow: 'ArtifactsDownload.yml'
+    secrets: inherit
+
+  PullRequest:
+    name: Create Pull-Request
+    runs-on: 'ubuntu-24.04'
+    needs:
+      - Prepare
+      - Verify-ProjectRoot
+      - Verify-SubDirectory
+      - Verify-MultipleArtifacts
+      - Verify-legacy
+    if: needs.Prepare.outputs.is_release_tag == 'true'
+    permissions:
+      contents: write
+      actions:  write
+    defaults:
+      run:
+        shell: bash
+
+    steps:
+      - name: ⏬ Checkout repository
+        uses: actions/checkout@v5
+        with:
+          # The command 'git describe' (used for version) needs the history.
+          fetch-depth: 0
+
+      - name: Create Pull-Request
+        run: |
+          set +e
+
+          ANSI_LIGHT_RED=$'\x1b[91m'
+          ANSI_LIGHT_GREEN=$'\x1b[92m'
+          ANSI_LIGHT_YELLOW=$'\x1b[93m'
+          ANSI_LIGHT_BLUE=$'\x1b[94m'
+          ANSI_NOCOLOR=$'\x1b[0m'
+
+          export GH_TOKEN=${{ github.token }}
+
+          title="Update v6 from ${{ needs.Prepare.outputs.version }}"
+
+          printf "Creating pull-request '${title}' ... "
+          gh pr create --base v6 --head main --title "${title}" --body "Auto generated"
+          if [[ $? -eq 0 ]]; then
+              printf "${ANSI_LIGHT_GREEN}[OK]${ANSI_NOCOLOR}\n"
+          else
+            printf "${ANSI_LIGHT_RED}[FAILED]${ANSI_NOCOLOR}\n"
+            printf "::error title=%s::%s\n" "GitHub PullRequest API" "Couldn't create pull-request."
+          fi
